In [1]:
import pandas as pd
import joblib
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("BANK LOAN.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SN         700 non-null    int64
 1   AGE        700 non-null    int64
 2   EMPLOY     700 non-null    int64
 3   ADDRESS    700 non-null    int64
 4   DEBTINC    700 non-null    float64
 5   CREDDEBT   700 non-null    float64
 6   OTHDEBT    700 non-null    float64
 7   DEFAULTER  700 non-null    int64
dtypes: float64(3), int64(5)
memory usage: 43.9 KB

In [2]:
df.head()

   SN  AGE  EMPLOY  ADDRESS  DEBTINC  CREDDEBT  OTHDEBT  DEFAULTER
0   1    3      17       12      9.3     11.36     5.01          1
1   2    1      10        6     17.3      1.36     4.00          0
2   3    2      15       14      5.5      0.86     2.17          0
3   4    3      15       14      2.9      2.66     0.82          0
4   5    1       2        0     17.3      1.79     3.06          1

In [3]:
test_df = pd.read_csv("BANK LOAN_TEST.csv")
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SN         10 non-null     int64
 1   AGE        10 non-null     int64
 2   EMPLOY     10 non-null     int64
 3   ADDRESS    10 non-null     int64
 4   DEBTINC    10 non-null     float64
 5   CREDDEBT   10 non-null     float64
 6   OTHDEBT    10 non-null     float64
 7   DEFAULTER  10 non-null     int64
dtypes: float64(3), int64(5)
memory usage: 768.0 bytes

In [4]:
test_df.head()

   SN  AGE  EMPLOY  ADDRESS  DEBTINC  CREDDEBT  OTHDEBT  DEFAULTER
0   1    3      16       10      9.1     11.30     5.01          1
1   2    1       8        5     17.0      1.46     4.00          0
2   3    2      15       14      5.5      0.86     2.17          0
3   4    3      13       13      2.9      2.56     0.82          0
4   5    1       2        1     16.5      1.79     3.06          1

In [5]:
X = df.drop(columns=["SN", "DEFAULTER"])
y = df["DEFAULTER"]

model = RandomForestClassifier(
    n_estimators=500,
    random_state=42
)

model.fit(X, y)
joblib.dump(model, "model.pkl")

print("Model trained successfully.")
print(f"Number of trees: {model.n_estimators}")
print(f"Features: {list(X.columns)}")
print("Model saved as model.pkl")

Model trained successfully.
Number of trees: 500
Features: ['AGE', 'EMPLOY', 'ADDRESS', 'DEBTINC', 'CREDDEBT', 'OTHDEBT']
Model saved as model.pkl

In [8]:
X_test = test_df.drop(columns=["SN"], errors='ignore')
X_test = X_test[["AGE","EMPLOY","ADDRESS","DEBTINC","CREDDEBT","OTHDEBT"]]

# predict default possibility
proba = model.predict_proba(X_test)[:,1]

test_df["Default_Probability"] = proba
test_df["Prediction"] = (proba > 0.5).astype(int)

test_df.to_csv("BankLoan_Test_Predicted.csv", index=False)
test_df.to_excel("BankLoan_Test_Predicted.xlsx", index=False)

print(test_df.head())
print("Test predictions saved -> BankLoan_Test_Predicted.csv")

   SN  AGE  EMPLOY  ADDRESS  DEBTINC  CREDDEBT  OTHDEBT  DEFAULTER  \
0   1    3      16       10      9.1     11.30     5.01          1
1   2    1       8        5     17.0      1.46     4.00          0
2   3    2      15       14      5.5      0.86     2.17          0
3   4    3      13       13      2.9      2.56     0.82          0
4   5    1       2        1     16.5      1.79     3.06          1

   Default_Probability  Prediction
0                0.680           1
1                0.318           0
2                0.000           0
3                0.086           0
4                0.784           1
Test predictions saved -> BankLoan_Test_Predicted.csv